//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowConsoleApplicationForAccountService.ServiceReferenceLoginNha {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceLoginNha.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LoginService", ReplyAction="http://tempuri.org/IService/LoginServiceResponse")]
        WorkflowConsoleApplicationForAccountService.ServiceReferenceLoginNha.LoginServiceResponse LoginService(WorkflowConsoleApplicationForAccountService.ServiceReferenceLoginNha.LoginServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LoginService", ReplyAction="http://tempuri.org/IService/LoginServiceResponse")]
        System.Threading.Tasks.Task<WorkflowConsoleApplicationForAccountService.ServiceReferenceLoginNha.LoginServiceResponse> LoginServiceAsync(WorkflowConsoleApplicationForAccountService.ServiceReferenceLoginNha.LoginServiceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginService", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Input_Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Input_Password;
        
        public LoginServiceRequest() {
        }
        
        public LoginServiceRequest(string Input_Username, string Input_Password) {
            this.Input_Username = Input_Username;
            this.Input_Password = Input_Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginServiceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool[] OutPut_ResultLogin;
        
        public LoginServiceResponse() {
        }
        
        public LoginServiceResponse(bool[] OutPut_ResultLogin) {
            this.OutPut_ResultLogin = OutPut_ResultLogin;
        }
    }
}
