//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowConsoleApplicationForAccountService.AccountServiceNha {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccountServiceNha.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AccountService", ReplyAction="http://tempuri.org/IService/AccountServiceResponse")]
        WorkflowConsoleApplicationForAccountService.AccountServiceNha.AccountServiceResponse AccountService(WorkflowConsoleApplicationForAccountService.AccountServiceNha.AccountServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AccountService", ReplyAction="http://tempuri.org/IService/AccountServiceResponse")]
        System.Threading.Tasks.Task<WorkflowConsoleApplicationForAccountService.AccountServiceNha.AccountServiceResponse> AccountServiceAsync(WorkflowConsoleApplicationForAccountService.AccountServiceNha.AccountServiceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AccountService", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AccountServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string input_Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string intput_Password;
        
        public AccountServiceRequest() {
        }
        
        public AccountServiceRequest(string input_Username, string intput_Password) {
            this.input_Username = input_Username;
            this.intput_Password = intput_Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AccountServiceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AccountServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool OutResult;
        
        public AccountServiceResponse() {
        }
        
        public AccountServiceResponse(bool OutResult) {
            this.OutResult = OutResult;
        }
    }
}
