//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowConsoleApplicationForAccountService.NewforcusServiceNha {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NewforcusServiceNha.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/NewForcusService", ReplyAction="http://tempuri.org/IService/NewForcusServiceResponse")]
        WorkflowConsoleApplicationForAccountService.NewforcusServiceNha.NewForcusServiceResponse NewForcusService(WorkflowConsoleApplicationForAccountService.NewforcusServiceNha.NewForcusServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/NewForcusService", ReplyAction="http://tempuri.org/IService/NewForcusServiceResponse")]
        System.Threading.Tasks.Task<WorkflowConsoleApplicationForAccountService.NewforcusServiceNha.NewForcusServiceResponse> NewForcusServiceAsync(WorkflowConsoleApplicationForAccountService.NewforcusServiceNha.NewForcusServiceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NewForcusService", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class NewForcusServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] Input_topic;
        
        public NewForcusServiceRequest() {
        }
        
        public NewForcusServiceRequest(string[] Input_topic) {
            this.Input_topic = Input_topic;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NewForcusServiceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class NewForcusServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] Output_Result;
        
        public NewForcusServiceResponse() {
        }
        
        public NewForcusServiceResponse(string[] Output_Result) {
            this.Output_Result = Output_Result;
        }
    }
}
